use crate::types::*;
use anyhow::{Context, Result};
use chrono::Utc;
use std::path::PathBuf;

pub struct ReportGenerator {
    output_dir: PathBuf,
}

impl ReportGenerator {
    pub fn new() -> Self {
        Self {
            output_dir: PathBuf::from(".palsphere/reports"),
        }
    }

    pub fn write_check_report(&self, result: &CheckResult) -> Result<PathBuf> {
        std::fs::create_dir_all(&self.output_dir)
            .context("Failed to create reports directory")?;

        let timestamp = Utc::now().format("%Y%m%d-%H%M%S");
        let safe_pkg = result.package.replace('/', "-").replace('@', "");
        let filename = format!("{}-{}-{}-check.md", timestamp, result.ecosystem, safe_pkg);
        let path = self.output_dir.join(&filename);

        let icon = match result.recommendation {
            Recommendation::Block => "🔴",
            Recommendation::Review => "🟡",
            Recommendation::Allow => "🟢",
            Recommendation::Unknown => "⚪",
        };

        let severity_str = result
            .highest_severity
            .as_ref()
            .map(|s| s.to_string())
            .unwrap_or_else(|| "none".to_string());

        let mut md = String::new();
        md.push_str(&format!("# {} Vulnerability Check\n\n", icon));
        md.push_str("| Field | Value |\n");
        md.push_str("|-------|-------|\n");
        md.push_str(&format!("| **Ecosystem** | {} |\n", result.ecosystem));
        md.push_str(&format!("| **Package** | `{}` |\n", result.package));
        md.push_str(&format!("| **Version** | {} |\n", result.version));
        md.push_str(&format!("| **Checked at** | {} |\n", result.checked_at));
        md.push_str(&format!(
            "| **Vulnerabilities** | {} |\n",
            result.vulnerability_count
        ));
        md.push_str(&format!("| **Highest Severity** | {} |\n", severity_str));
        md.push_str(&format!("| **Risk Score** | {}/100 |\n", result.risk_score));
        md.push_str(&format!(
            "| **Recommendation** | **{:?}** |\n\n",
            result.recommendation
        ));
        md.push_str(&format!("## Summary\n\n{}\n\n", result.summary));

        if !result.vulnerabilities.is_empty() {
            md.push_str("## Vulnerabilities\n\n");
            for (i, vuln) in result.vulnerabilities.iter().enumerate() {
                md.push_str(&format!(
                    "### {}. {}\n\n",
                    i + 1,
                    vuln.summary.as_deref().unwrap_or(&vuln.id)
                ));
                md.push_str(&format!("- **ID:** `{}`\n", vuln.id));
                if let Some(sev) = &vuln.severity {
                    md.push_str(&format!("- **Severity:** {}\n", sev));
                }
                if !vuln.fixed_versions.is_empty() {
                    md.push_str(&format!(
                        "- **Fixed in:** {}\n",
                        vuln.fixed_versions.join(", ")
                    ));
                }
                if let Some(url) = &vuln.advisory_url {
                    md.push_str(&format!("- **Advisory:** {}\n", url));
                }
                md.push('\n');
            }
        }

        md.push_str("---\n\n*Generated by [palsphere](https://github.com/faizalardhi16/palsphere)*\n");

        std::fs::write(&path, &md).context("Failed to write report file")?;
        Ok(path)
    }

    pub fn write_compare_report(&self, result: &CompareResult) -> Result<PathBuf> {
        std::fs::create_dir_all(&self.output_dir)
            .context("Failed to create reports directory")?;

        let timestamp = Utc::now().format("%Y%m%d-%H%M%S");
        let safe_pkg = result.package.replace('/', "-").replace('@', "");
        let filename = format!(
            "{}-{}-{}-compare.md",
            timestamp, result.ecosystem, safe_pkg
        );
        let path = self.output_dir.join(&filename);

        let icon = if result.risk_improved { "✅" } else { "⚠️" };
        let score_diff = result.from_risk_score as i16 - result.to_risk_score as i16;

        let mut md = String::new();
        md.push_str(&format!("# {} Version Comparison\n\n", icon));
        md.push_str("| Field | Value |\n");
        md.push_str("|-------|-------|\n");
        md.push_str(&format!("| **Ecosystem** | {} |\n", result.ecosystem));
        md.push_str(&format!("| **Package** | `{}` |\n", result.package));
        md.push_str(&format!(
            "| **From** | {} (risk: {}/100) |\n",
            result.from_version, result.from_risk_score
        ));
        md.push_str(&format!(
            "| **To** | {} (risk: {}/100) |\n",
            result.to_version, result.to_risk_score
        ));
        md.push_str(&format!(
            "| **Risk Change** | {} |\n",
            if score_diff > 0 {
                format!("Improved by {} points", score_diff)
            } else if score_diff < 0 {
                format!("Worsened by {} points", -score_diff)
            } else {
                "No change".to_string()
            }
        ));
        md.push_str(&format!(
            "| **Recommendation** | {:?} |\n",
            result.recommendation
        ));
        md.push_str(&format!("| **Action** | {} |\n\n", result.next_action));

        if !result.resolved_vulnerabilities.is_empty() {
            md.push_str("## Resolved Vulnerabilities\n\n");
            for id in &result.resolved_vulnerabilities {
                md.push_str(&format!("- `{}`\n", id));
            }
            md.push('\n');
        }

        if !result.added_vulnerabilities.is_empty() {
            md.push_str("## New Vulnerabilities\n\n");
            for id in &result.added_vulnerabilities {
                md.push_str(&format!("- `{}`\n", id));
            }
            md.push('\n');
        }

        md.push_str("---\n\n*Generated by [palsphere](https://github.com/faizalardhi16/palsphere)*\n");

        std::fs::write(&path, &md).context("Failed to write report file")?;
        Ok(path)
    }
}
